server:
  port: 9004 #服务访问端口号
spring:
  application:
    name: sns-article #服务名称
  datasource:
    driver-class-name: com.mysql.jdbc.Driver #服务连接的属性
    url: jdbc:mysql://192.168.25.133:3306/sns_article?characterEncoding=utf-8
    username: root
    password: root
  data: #整合mongodb的配置
    mongodb:
      database: commentdb
      host: 192.168.25.133
  redis:
    host: 192.168.25.133
  rabbitmq:
    host: 192.168.25.133
#mybatis-plus:
#  #  mapper-locations: classpath:/mapper/*Mapper.xml
#  #实体扫描，多个package用逗号或者分号分隔
#  typeAliasesPackage: com.zrkworld.sns.article.pojo
#  #别名包扫描路径，通过该属性可以给包中的类注册别名，注册后在 Mapper 对应的 XML 文件中可以直接使用类名，而不用使用全限定的类名(即 XML 中调用的时候不用包含包名)
#  global-config:
#    db-config:
#      id-type: assign_id  #0:数据库ID自增   1:用户输入id
#      #logic-delete-value: 0
#      #logic-not-delete-value: 1
#      field-strategy: not_empty
#
#      #逻辑删除配置
#      db-type: mysql
#      refresh-mapper: true
#  configuration:
#    map-underscore-to-camel-case: false #取消将驼峰命名改为下划线字段名
#    cache-enabled: true #配置的缓存的全局开关
#    lazyLoadingEnabled: true #延时加载的开关
#    multipleResultSetsEnabled: true #开启延时加载，否则按需加载属性
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql语句,调试用
#
# Mybatis-Plus 配置
mybatis-plus:
  #  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.zrkworld.sns.article.pojo
  global-config:
    id-type: 1  #0:数据库ID自增   1:用户输入id
    db-column-underline: false
    refresh-mapper: true
    column-underline: true
  configuration:
    map-underscore-to-camel-case: false #取消将驼峰命名改为下划线字段名
    cache-enabled: true #配置的缓存的全局开关
    lazyLoadingEnabled: true #延时加载的开关
    multipleResultSetsEnabled: true #开启延时加载，否则按需加载属性
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql语句,调试用

#eureka配置
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka/
  instance:
    prefer-ip-address: true